const pictureList = [
  {
    id: 1,
    name: "Baseball (Semi - Professional Baseball)",
    author: "Ernest N Morse",
    description: "Baseball (Semi - Professional Baseball)",
    url: "../images/IMG_0913 (2).png",
    alt: "Baseball",
  },
  {
    id: 2,
    name: "Natural Bodybuilding / Weightlifting",
    author: "Ernest N Morse",
    description: "Natural Bodybuilding / Weightlifting",
    url: "../images/IMG_0910 (2).png",
    alt: "Natural Bodybuilding / Weightlifting",
  },
  {
    id: 3,
    name: "Golf (Long Drivers Of America)",
    author: "Ernest N Morse",
    description: "GOLF",
    url: "../images/IMG_0912 (3).png",
    alt: "GOLF",
  },
  {
    id: 4,
    name: "SCA (Society of Creative Anachronism)",
    author: "Ernest N Morse",
    description: "SCA Heavy Combat",
    url: "../images/IMG_0916 (3).png",
    alt: "Society of Creative Anachronism",
  },
  {
    id: 5,
    name: "AD&D / D&D (Dungeons & Dragons)",
    author: "Ernest N Morse",
    description: "AD&D / D&D",
    url: "../images/IMG_0920 (2).png",
    alt: "Advanced D&D / D&D",
  },
  {
    id: 6,
    name: "Web Development",
    author: "Ernest N Morse",
    description: "Web Development",
    url: "../images/IMG_0922.png",
    alt: "Web Development",
  },
  {
    id: 7,
    name: "D&D / D&D Novels",
    author: "Ernest N Morse",
    description: "D&D / D&D Novels",
    url: "../images/IMG_4659-scaled (4).jpg",
    alt: "Forgotten Realms / Dragonlance",
  },
  {
    id: 8,
    name: "Web Development",
    author: "Ernest N Morse",
    description: "Web Development",
    url: "../images/pexels-negative-space-169573.jpg",
    alt: "Web Development",
  },
  {
    id: 9,
    name: "D&D / D&D Novels",
    author: "Ernest N Morse",
    description: "D&D / D&D Novels",
    url: "../images/wdgTkhN5.jpg",
    alt: "Forgotten Realms / Dragonlance",
  },
];

export default pictureList;
